#!/bin/bash

set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -c \
    "GRANT CONNECT ON DATABASE \"$POSTGRES_DB\" TO \"$POSTGRES_CLIENTUSER\";
    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO $POSTGRES_CLIENTUSER;"
